//! Emits `api.model.json`.
//!
//! This is the file every binding generator reads. It is checked in so that a
//! generator can run without a Rust toolchain, and CI regenerates it and fails
//! on a diff, so checked in never means stale.

use crate::json::Out;
use crate::model::{ABI_MAJOR, ABI_MINOR, FUNCS, HANDLES};
use crate::{errors, root};

/// Renders the model.
pub fn render() -> String {
    let errs = errors::load(&root());
    let mut o = Out::new();
    o.obj();

    o.str(
        "note",
        "Generated by `cargo xtask generate`. Do not edit. The source is xtask/src/model.rs and crates/yo-common/errors.toml.",
    );
    o.obj_at("abi");
    o.num("major", ABI_MAJOR as u64);
    o.num("minor", ABI_MINOR as u64);
    // Major zero means the shapes can still move. Anything from one onwards is
    // a promise, and a binding generator can read this flag to decide whether
    // it is allowed to cache what it saw last time.
    o.bool("frozen", ABI_MAJOR != 0);
    o.end_obj();

    o.arr_at("handles");
    for h in HANDLES {
        o.obj();
        o.str("name", h.name);
        o.bool("shareable", h.shareable);
        o.str("closer", h.closer);
        o.str("doc", h.doc);
        o.end_obj();
    }
    o.end_arr();

    o.arr_at("errors");
    for e in &errs {
        o.obj();
        o.str("name", &e.name);
        o.num("code", e.code as u64);
        o.str("c_name", &e.c_name);
        o.bool("retryable", e.retryable);
        o.str("doc", &e.doc);
        o.opt_str("url", e.url.as_deref());
        o.end_obj();
    }
    o.end_arr();

    o.arr_at("functions");
    for f in FUNCS {
        o.obj();
        o.str("symbol", f.symbol);
        o.str("kind", f.kind.as_str());
        o.str("cost_class", f.cost.as_str());
        o.str("returns", f.returns);
        o.str("returns_ownership", f.returns_own.as_str());
        o.arr_at("params");
        for p in f.params {
            o.obj();
            o.str("name", p.name);
            o.str("type", p.ty);
            o.str("ownership", p.own.as_str());
            o.str("doc", p.doc);
            o.end_obj();
        }
        o.end_arr();
        o.bool("takes_error", f.errors);
        o.bool("batchable", f.many.is_some());
        o.opt_str("many", f.many);
        o.num("since", f.since as u64);
        o.strs("doc", f.doc);
        o.opt_str("example_id", f.example);
        o.end_obj();
    }
    o.end_arr();

    o.end_obj();
    o.finish()
}

#[cfg(test)]
mod tests {
    use crate::model::{Cost, FUNCS, HANDLES, Kind};
    use std::collections::HashSet;

    // These are the rules dx/03 section 8 says CI enforces. They are checked
    // here, against the model, rather than in a shell script over the output,
    // because a rule about the model belongs to the model.

    #[test]
    fn every_single_key_read_has_a_many_form() {
        let known: HashSet<&str> = FUNCS.iter().map(|f| f.symbol).collect();
        for f in FUNCS {
            let single_key = f.params.iter().any(|p| p.name == "key");
            if f.kind == Kind::Read && single_key {
                let many = f.many.unwrap_or_else(|| {
                    panic!("{} is a single key read with no _many form", f.symbol)
                });
                assert!(
                    known.contains(many),
                    "{} names a _many form that does not exist",
                    f.symbol
                );
            }
        }
    }

    #[test]
    fn every_handle_has_exactly_one_closer() {
        let known: HashSet<&str> = FUNCS.iter().map(|f| f.symbol).collect();
        for h in HANDLES {
            assert!(
                known.contains(h.closer),
                "{} names a closer that does not exist",
                h.name
            );
        }
        for f in FUNCS.iter().filter(|f| f.kind == Kind::Destructor) {
            assert!(
                HANDLES.iter().any(|h| h.closer == f.symbol),
                "{} destroys something no handle claims",
                f.symbol
            );
        }
    }

    #[test]
    fn symbols_are_unique_and_prefixed() {
        let mut seen = HashSet::new();
        for f in FUNCS {
            assert!(
                f.symbol.starts_with("yo_"),
                "{} is not namespaced",
                f.symbol
            );
            assert!(seen.insert(f.symbol), "{} appears twice", f.symbol);
        }
    }

    #[test]
    fn a_read_or_write_can_report_an_error() {
        for f in FUNCS
            .iter()
            .filter(|f| matches!(f.kind, Kind::Read | Kind::Write))
        {
            // yo_len is the exception and it is allowed to be: it cannot fail,
            // and a call that cannot fail should not make the caller declare an
            // error variable to prove it.
            if f.symbol == "yo_len" {
                continue;
            }
            assert!(f.errors, "{} can fail and has nowhere to say so", f.symbol);
        }
    }

    #[test]
    fn nothing_that_touches_data_is_free() {
        for f in FUNCS
            .iter()
            .filter(|f| matches!(f.kind, Kind::Read | Kind::Write))
        {
            if f.symbol == "yo_len" {
                continue;
            }
            assert_ne!(f.cost, Cost::Free, "{} claims to cost nothing", f.symbol);
        }
    }

    #[test]
    fn every_entry_documents_itself() {
        for f in FUNCS {
            assert!(!f.doc.is_empty(), "{} has no doc", f.symbol);
            assert!(
                !f.doc[0].is_empty(),
                "{} starts its doc with a blank line",
                f.symbol
            );
            for p in f.params {
                assert!(
                    !p.doc.is_empty(),
                    "{} parameter {} has no doc",
                    f.symbol,
                    p.name
                );
            }
        }
    }

    #[test]
    fn the_model_renders_and_looks_like_json() {
        let s = super::render();
        assert!(s.starts_with('{'));
        assert!(s.ends_with("}\n"));
        assert!(s.contains("\"symbol\": \"yo_get_many\""));
        assert!(s.contains("\"cost_class\": \"probe\""));
    }
}
