//! Emits `include/yo.h`.
//!
//! The header has to compile clean under `-Wall -Wextra -Wpedantic` as C99
//! through C23 and as C++17 through C++23, on gcc, clang and MSVC. That rules
//! out a few habits: no `//` comments, no trailing comma in an enum, no anonymous
//! unions, no `bool` without a header, no zero sized arrays. The emitter sticks
//! to the intersection on purpose, and the C example job in CI is what proves it.

use crate::model::{ABI_MAJOR, ABI_MINOR, FUNCS, HANDLES, Kind};
use crate::{errors, root};
use std::fmt::Write as _;

/// Renders the header.
pub fn render() -> String {
    let errs = errors::load(&root());
    let mut h = String::new();

    h.push_str("/* Generated by `cargo xtask generate`. Do not edit.\n");
    h.push_str(" *\n");
    h.push_str(" * The source is xtask/src/model.rs and crates/yo-common/errors.toml.\n");
    h.push_str(" * CI regenerates this file and fails on a diff.\n");
    h.push_str(" *\n");
    h.push_str(" * yo, an embedded knowledge engine.\n");
    h.push_str(" * SPDX-License-Identifier: MIT OR Apache-2.0\n");
    h.push_str(" */\n\n");

    h.push_str("#ifndef YO_H\n#define YO_H\n\n");
    h.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    h.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    h.push_str("/* Visibility. Define YO_STATIC when linking the static library. */\n");
    h.push_str("#if defined(YO_STATIC)\n");
    h.push_str("#  define YO_API\n");
    h.push_str("#elif defined(_WIN32)\n");
    h.push_str("#  if defined(YO_BUILDING)\n");
    h.push_str("#    define YO_API __declspec(dllexport)\n");
    h.push_str("#  else\n");
    h.push_str("#    define YO_API __declspec(dllimport)\n");
    h.push_str("#  endif\n");
    h.push_str("#else\n");
    h.push_str("#  define YO_API __attribute__((visibility(\"default\")))\n");
    h.push_str("#endif\n\n");

    writeln!(h, "#define YO_ABI_VERSION_MAJOR {ABI_MAJOR}").unwrap();
    writeln!(h, "#define YO_ABI_VERSION_MINOR {ABI_MINOR}").unwrap();
    h.push('\n');
    h.push_str("/* The largest batch one crossing may carry.\n * Matches BATCH_MAX in 04 section 3.\n */\n");
    writeln!(h, "#define YO_BATCH_MAX {}", yo_common::BATCH_MAX).unwrap();
    h.push('\n');

    h.push_str("/* Condition codes. Generated from errors.toml, never renumbered. */\n");
    h.push_str("typedef enum yo_code {\n");
    for (i, e) in errs.iter().enumerate() {
        block_comment(&mut h, 2, &[&e.doc]);
        let comma = if i + 1 == errs.len() { "" } else { "," };
        writeln!(h, "  {} = {}{}", e.c_name, e.code, comma).unwrap();
    }
    h.push_str("} yo_code;\n\n");

    h.push_str("/* A borrowed run of bytes. The engine reads it during the call and does\n");
    h.push_str(" * not retain it, unless a specific call says otherwise.\n */\n");
    h.push_str("typedef struct yo_slice {\n");
    h.push_str("  const uint8_t *ptr;\n");
    h.push_str("  uint64_t len;\n");
    h.push_str("} yo_slice;\n\n");

    h.push_str("/* An error. Set `size` to sizeof(yo_error) before the call. The engine\n");
    h.push_str(" * reads it and writes only the fields your build knows about, which is\n");
    h.push_str(" * how this struct grows without breaking a binary compiled today.\n");
    h.push_str(" *\n");
    h.push_str(" * All five reportable fields cross the boundary, including the multi\n");
    h.push_str(" * line `detail` that carries a shape diff. A binding that flattens this\n");
    h.push_str(" * into one message string has thrown away the part users need.\n */\n");
    h.push_str("typedef struct yo_error {\n");
    h.push_str("  uint32_t size;\n");
    h.push_str("  yo_code code;\n");
    h.push_str("  uint8_t retryable;\n");
    h.push_str("  const char *message;\n");
    h.push_str("  const char *position;\n");
    h.push_str("  const char *url;\n");
    h.push_str("  const char *detail;\n");
    h.push_str("} yo_error;\n\n");
    h.push_str("#define YO_ERROR_INIT { (uint32_t)sizeof(yo_error), YO_OK, 0, 0, 0, 0, 0 }\n\n");

    h.push_str("/* Open options. Caller laid out, so it carries a leading size too. Pass NULL\n");
    h.push_str(" * to yo_open for the defaults.\n */\n");
    h.push_str("typedef struct yo_open_options {\n");
    h.push_str("  uint32_t size;\n");
    h.push_str("  /* Shard threads. 0 means one per core, 1 means run inline on the\n");
    h.push_str("   * calling thread, which is the mode the sixty second snippet uses.\n   */\n");
    h.push_str("  uint32_t shards;\n");
    h.push_str("  /* Non zero opens the file without taking the writer lock. */\n");
    h.push_str("  uint8_t read_only;\n");
    h.push_str("} yo_open_options;\n\n");
    h.push_str("#define YO_OPEN_OPTIONS_INIT { (uint32_t)sizeof(yo_open_options), 0, 0 }\n\n");

    h.push_str("/* Handles. Opaque pointers into engine memory, never table indexes: an\n");
    h.push_str(" * index handle turns a use after free into silent corruption, and a\n");
    h.push_str(" * pointer turns it into a crash you can debug.\n */\n");
    for hd in HANDLES {
        block_comment(&mut h, 0, &[hd.doc, "", &thread_note(hd.shareable)]);
        writeln!(h, "typedef struct {0} {0};", hd.name).unwrap();
    }
    h.push('\n');

    for f in FUNCS {
        let mut lines: Vec<String> = f.doc.iter().map(|s| s.to_string()).collect();
        lines.push(String::new());
        lines.push(format!("Cost: {}.", f.cost.as_str()));
        if let Some(m) = f.many {
            lines.push(format!("Batched form: {m}."));
        }
        if f.errors {
            lines.push("On failure `err` is populated and the return says so.".to_string());
        }
        if f.kind == Kind::Constructor {
            let closer = HANDLES
                .iter()
                .find(|hd| f.returns.starts_with(hd.name))
                .map(|hd| hd.closer);
            if let Some(c) = closer {
                lines.push(format!("Release with {c}."));
            }
        }
        let refs: Vec<&str> = lines.iter().map(|s| s.as_str()).collect();
        block_comment(&mut h, 0, &refs);

        write!(h, "YO_API {}{}", f.returns, spacer(f.returns)).unwrap();
        write!(h, "{}(", f.symbol).unwrap();
        let mut args: Vec<String> = f
            .params
            .iter()
            .map(|p| format!("{}{}{}", p.ty, spacer(p.ty), p.name))
            .collect();
        if f.errors {
            args.push("yo_error *err".to_string());
        }
        if args.is_empty() {
            h.push_str("void");
            h.push_str(");\n\n");
        } else {
            // One line while it fits, one parameter per line once it does not.
            // A declaration that wraps at whatever column the terminal happens
            // to be is the sort of thing that makes a generated header look
            // untended.
            let head = h.len() - h.rfind('\n').map_or(0, |i| i + 1);
            let joined = args.join(", ");
            if head + joined.len() + 2 <= 80 {
                h.push_str(&joined);
            } else {
                h.push('\n');
                for (i, a) in args.iter().enumerate() {
                    let tail = if i + 1 == args.len() { "" } else { "," };
                    writeln!(h, "    {a}{tail}").unwrap();
                }
                h.truncate(h.len() - 1);
            }
            h.push_str(");\n\n");
        }
    }

    h.push_str("#ifdef __cplusplus\n}\n#endif\n\n#endif /* YO_H */\n");
    h
}

/// C types that already end in a star do not want another space before the name.
fn spacer(ty: &str) -> &'static str {
    if ty.ends_with('*') { "" } else { " " }
}

fn thread_note(shareable: bool) -> String {
    if shareable {
        "Safe to use from more than one thread at a time.".to_string()
    } else {
        "Not thread safe. The debug build records the creating thread and asserts.".to_string()
    }
}

/// A block comment, since `//` is not C89 and MSVC still cares in some modes.
///
/// Doc text in the model is written as prose and is not wrapped, because the
/// same sentence has to come out as a Python docstring, a Javadoc block and a
/// TypeScript comment. Wrapping is the emitter's job, per target.
fn block_comment(h: &mut String, indent: usize, lines: &[&str]) {
    let pad = " ".repeat(indent);
    // The prefix is the indent plus ` * `, and the target is 80 columns.
    let wrapped: Vec<String> = lines.iter().flat_map(|l| wrap(l, 76 - indent)).collect();
    if wrapped.len() == 1 && wrapped[0].len() + indent + 6 <= 80 {
        writeln!(h, "{pad}/* {} */", wrapped[0]).unwrap();
        return;
    }
    writeln!(h, "{pad}/* {}", wrapped[0]).unwrap();
    for l in &wrapped[1..] {
        if l.is_empty() {
            writeln!(h, "{pad} *").unwrap();
        } else {
            writeln!(h, "{pad} * {l}").unwrap();
        }
    }
    writeln!(h, "{pad} */").unwrap();
}

/// Greedy wrap on spaces. A word longer than the width goes on its own line
/// rather than being broken, because the long words here are identifiers.
fn wrap(line: &str, width: usize) -> Vec<String> {
    if line.is_empty() {
        return vec![String::new()];
    }
    let mut out = Vec::new();
    let mut cur = String::new();
    for word in line.split(' ') {
        if cur.is_empty() {
            cur.push_str(word);
        } else if cur.len() + 1 + word.len() <= width {
            cur.push(' ');
            cur.push_str(word);
        } else {
            out.push(std::mem::take(&mut cur));
            cur.push_str(word);
        }
    }
    out.push(cur);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_header_has_the_shape_a_c_compiler_expects() {
        let h = render();
        assert!(h.contains("#ifndef YO_H"));
        assert!(h.trim_end().ends_with("#endif /* YO_H */"));
        assert_eq!(h.matches("extern \"C\" {").count(), 1);
        assert_eq!(h.matches("#ifdef __cplusplus").count(), 2);
    }

    #[test]
    fn no_line_comments_anywhere() {
        // `//` is fine in C99 and later but the header claims C89 tolerance in
        // its own docs, and MSVC in /Za still objects. Cheaper to never emit one.
        for (i, line) in render().lines().enumerate() {
            assert!(
                !line.contains("//"),
                "line {} uses a line comment: {line}",
                i + 1
            );
        }
    }

    #[test]
    fn every_symbol_in_the_model_is_declared_once() {
        let h = render();
        for f in FUNCS {
            let decl = format!("{}(", f.symbol);
            assert_eq!(
                h.matches(&decl).count(),
                1,
                "{} is not declared exactly once",
                f.symbol
            );
        }
    }

    #[test]
    fn the_enum_has_no_trailing_comma() {
        let h = render();
        let body = h.split("typedef enum yo_code {").nth(1).unwrap();
        let body = body.split("} yo_code;").next().unwrap();
        let last = body.lines().rfind(|l| !l.trim().is_empty()).unwrap();
        assert!(
            !last.trim_end().ends_with(','),
            "trailing comma in the enum: {last}"
        );
    }

    #[test]
    fn nothing_runs_past_eighty_columns() {
        for (i, line) in render().lines().enumerate() {
            assert!(
                line.len() <= 80,
                "line {} is {} columns and a header nobody can read is a header nobody checks: {line}",
                i + 1,
                line.len()
            );
        }
    }

    #[test]
    fn pointer_types_do_not_get_a_double_space() {
        for line in render().lines().filter(|l| l.starts_with("YO_API")) {
            assert!(!line.contains("*  "), "double spaced pointer: {line}");
            assert!(
                !line.contains("  "),
                "double space in a declaration: {line}"
            );
        }
    }
}
