/* Generated by `cargo xtask generate`. Do not edit.
 *
 * The source is xtask/src/model.rs and crates/yo-common/errors.toml.
 * CI regenerates this file and fails on a diff.
 *
 * yo, an embedded knowledge engine.
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#ifndef YO_H
#define YO_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Visibility. Define YO_STATIC when linking the static library. */
#if defined(YO_STATIC)
#  define YO_API
#elif defined(_WIN32)
#  if defined(YO_BUILDING)
#    define YO_API __declspec(dllexport)
#  else
#    define YO_API __declspec(dllimport)
#  endif
#else
#  define YO_API __attribute__((visibility("default")))
#endif

#define YO_ABI_VERSION_MAJOR 0
#define YO_ABI_VERSION_MINOR 1

/* The largest batch one crossing may carry.
 * Matches BATCH_MAX in 04 section 3.
 */
#define YO_BATCH_MAX 64

/* Condition codes. Generated from errors.toml, never renumbered. */
typedef enum yo_code {
  /* Not an error. Present so that the C enum has a zero value that means
   * success.
   */
  YO_OK = 0,
  /* The type used to open a collection does not match the type the collection
   * was created with. The message carries both shape descriptions in full, not
   * just the tags.
   */
  YO_ERR_SHAPE_MISMATCH = 1,
  /* Another process holds the writer lock on this file. Exactly one writer per
   * file.
   */
  YO_ERR_LOCKED = 2,
  /* The handle has live children. Closing a parent with live children closes
   * nothing.
   */
  YO_ERR_BUSY = 3,
  /* The key, field, member or node does not exist. This is a value and not a
   * failure, and the typed API returns an Option rather than this error
   * wherever it can.
   */
  YO_ERR_NOT_FOUND = 4,
  /* The key holds a different data structure than the operation expects. This
   * is Redis WRONGTYPE.
   */
  YO_ERR_WRONG_TYPE = 5,
  /* The header the caller compiled against and the library it loaded disagree.
   * The message names both versions.
   */
  YO_ERR_ABI_MISMATCH = 6,
  /* A checksum failed or a structure is self-inconsistent. The message names
   * the offset and what was expected there.
   */
  YO_ERR_CORRUPT = 7,
  /* A bounded resource is exhausted: the address space, a fixed table, or a
   * configured memory limit.
   */
  YO_ERR_FULL = 8,
  /* The operating system refused an operation. The detail field carries errno
   * and the path.
   */
  YO_ERR_IO = 9,
  /* The operation is valid but this build or this platform does not implement
   * it. The message says which build would.
   */
  YO_ERR_UNSUPPORTED = 10,
  /* The arguments are wrong. The position field points at which one. */
  YO_ERR_INVALID = 11,
  /* An iterator has been open long enough to hold back reclamation. Finish it
   * or drop it. The message carries the iterator age in microseconds.
   */
  YO_ERR_EPOCH_STALLED = 12,
  /* The file's min_reader_version is higher than this build supports. The
   * message names both numbers and the release that would read it.
   */
  YO_ERR_VERSION_TOO_NEW = 13
} yo_code;

/* A borrowed run of bytes. The engine reads it during the call and does
 * not retain it, unless a specific call says otherwise.
 */
typedef struct yo_slice {
  const uint8_t *ptr;
  uint64_t len;
} yo_slice;

/* An error. Set `size` to sizeof(yo_error) before the call. The engine
 * reads it and writes only the fields your build knows about, which is
 * how this struct grows without breaking a binary compiled today.
 *
 * All five reportable fields cross the boundary, including the multi
 * line `detail` that carries a shape diff. A binding that flattens this
 * into one message string has thrown away the part users need.
 */
typedef struct yo_error {
  uint32_t size;
  yo_code code;
  uint8_t retryable;
  const char *message;
  const char *position;
  const char *url;
  const char *detail;
} yo_error;

#define YO_ERROR_INIT { (uint32_t)sizeof(yo_error), YO_OK, 0, 0, 0, 0, 0 }

/* Open options. Caller laid out, so it carries a leading size too. Pass NULL
 * to yo_open for the defaults.
 */
typedef struct yo_open_options {
  uint32_t size;
  /* Shard threads. 0 means one per core, 1 means run inline on the
   * calling thread, which is the mode the sixty second snippet uses.
   */
  uint32_t shards;
  /* Non zero opens the file without taking the writer lock. */
  uint8_t read_only;
} yo_open_options;

#define YO_OPEN_OPTIONS_INIT { (uint32_t)sizeof(yo_open_options), 0, 0 }

/* Handles. Opaque pointers into engine memory, never table indexes: an
 * index handle turns a use after free into silent corruption, and a
 * pointer turns it into a crash you can debug.
 */
/* The database. One per process per path. It belongs to the thread that opened
 * it for as long as inline mode is the only mode, and it becomes shareable
 * when owned mode lands; widening that guarantee later is compatible and
 * claiming it now would not be true.
 *
 * Not thread safe. The debug build records the creating thread and asserts.
 */
typedef struct yo_db yo_db;
/* Caller scoped result storage. Everything the engine writes for you lands
 * here.
 *
 * Not thread safe. The debug build records the creating thread and asserts.
 */
typedef struct yo_arena yo_arena;

/* The ABI version as (major << 16) | minor.
 *
 * Call this at load time. A binding that sees a different major refuses to
 * proceed and reports YO_ERR_ABI_MISMATCH naming both versions, because a
 * major mismatch means the struct layouts below have moved.
 *
 * Cost: free.
 */
YO_API uint32_t yo_abi_version(void);

/* The engine version, as a NUL terminated string that lives forever.
 *
 * This is the crate version and it moves independently of the ABI version.
 *
 * Cost: free.
 */
YO_API const char *yo_version_string(void);

/* Does nothing, on purpose.
 *
 * Every binding publishes the round trip cost of this call next to its own
 * overhead number, so that the split between what the FFI costs and what the
 * binding costs is visible rather than argued about (dx/03 section 6).
 *
 * Cost: free.
 */
YO_API void yo_noop(void);

/* The spelling of a code, for a build that does not know it.
 *
 * A binding compiled against an older header will meet codes it has no name
 * for. That is a value to report, not a crash, so this never returns NULL.
 *
 * Cost: free.
 */
YO_API const char *yo_code_name(uint32_t code);

/* Whether the identical call could succeed later.
 *
 * Generated from errors.toml, so retryability is a property of the condition
 * and never a judgement made at a call site.
 *
 * Cost: free.
 */
YO_API uint8_t yo_code_retryable(uint32_t code);

/* Opens an arena for results.
 *
 * Make one per call site, or per request, or per iteration batch. Reset it
 * between uses and free it once. This is what turns a loop over ten thousand
 * results into one allocation rather than ten thousand, and it is the whole
 * reason a binding in a managed language can stay inside the 3x budget.
 *
 * Cost: free.
 * On failure `err` is populated and the return says so.
 * Release with yo_arena_free.
 */
YO_API yo_arena *yo_arena_new(yo_db *db, yo_error *err);

/* Rewinds the arena and keeps its capacity.
 *
 * Every borrowed view into this arena is invalid the instant this returns,
 * and not one instruction longer. The debug build poisons the memory so that
 * a binding which gets this wrong fails in its own test suite.
 *
 * Cost: free.
 */
YO_API void yo_arena_reset(yo_arena *arena);

/* Frees the arena. Idempotent in the sense that NULL is fine.
 *
 * Cost: free.
 */
YO_API void yo_arena_free(yo_arena *arena);

/* Bytes handed out since the last reset.
 *
 * Bindings use this in their own tests to prove that a batched read really
 * did cost one arena bump per row and not one malloc per row.
 *
 * Cost: free.
 */
YO_API uint64_t yo_arena_used(const yo_arena *arena);

/* Opens a database.
 *
 * At this milestone the path is accepted and ignored: nothing is written to
 * disk until the record plane lands. Passing NULL is the honest way to ask
 * for what you actually get today.
 *
 * Cost: fault.
 * On failure `err` is populated and the return says so.
 * Release with yo_close.
 */
YO_API yo_db *yo_open(
    const char *path,
    const yo_open_options *opts,
    yo_error *err);

/* Closes the database. NULL is fine.
 *
 * Closing with live children frees nothing and is a bug in the binding, not
 * in the caller. The debug build asserts on it.
 *
 * Cost: free.
 */
YO_API void yo_close(yo_db *db);

/* Stores a value under a key. Returns 0, or -1 with err populated.
 *
 * Cost: probe.
 * On failure `err` is populated and the return says so.
 */
YO_API int32_t yo_set(yo_db *db, yo_slice key, yo_slice value, yo_error *err);

/* Reads a value without copying it. Returns 1 found, 0 missing, -1 error.
 *
 * The view points into the engine and stays valid until the next write to
 * this database. If you cannot promise that, use yo_get_copy.
 *
 * Cost: probe.
 * Batched form: yo_get_many.
 * On failure `err` is populated and the return says so.
 */
YO_API int32_t yo_get(yo_db *db, yo_slice key, yo_slice *out, yo_error *err);

/* Reads a value into the arena. Returns 1 found, 0 missing, -1 error.
 *
 * This is the default in every managed language, and it costs one arena bump
 * rather than one allocation.
 *
 * Cost: probe.
 * Batched form: yo_get_many.
 * On failure `err` is populated and the return says so.
 */
YO_API int32_t yo_get_copy(
    yo_db *db,
    yo_slice key,
    yo_arena *arena,
    yo_slice *out,
    yo_error *err);

/* Reads many keys in one crossing. Returns how many were found, or -1.
 *
 * This exists because the per call overhead in Python and Node is the binding
 * constraint, and amortising one crossing over 64 keys turns a 450 ns problem
 * into a 40 ns one. Every point read in this ABI has a _many form, by rule of
 * the generator rather than by anyone's judgement.
 *
 * Cost: probe.
 * On failure `err` is populated and the return says so.
 */
YO_API int32_t yo_get_many(
    yo_db *db,
    const yo_slice *keys,
    uint32_t n,
    yo_arena *arena,
    yo_slice *out,
    yo_error *err);

/* Removes a key. Returns 1 removed, 0 absent, -1 error.
 *
 * Cost: probe.
 * On failure `err` is populated and the return says so.
 */
YO_API int32_t yo_del(yo_db *db, yo_slice key, yo_error *err);

/* How many keys are live.
 *
 * Cost: free.
 */
YO_API uint64_t yo_len(const yo_db *db);

#ifdef __cplusplus
}
#endif

#endif /* YO_H */
